org.gradle.daemon=true
org.gradle.jvmargs=-Xms128m -Xmx2000m
org.gradle.configureondemand=false
android.useAndroidX=true

group=com.amilego.gdx
version=1.14.2-SNAPSHOT
POM_NAME=libGDX
POM_DESCRIPTION=Android/Desktop/iOS/HTML5 game development framework, modified by AmiLego
POM_URL=https://github.com/AmiLego/libgdx
POM_SCM_URL=https://github.com/AmiLego/libgdx
POM_SCM_CONNECTION=scm:git@github.com:AmiLego/libgdx.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:AmiLego/libgdx.git
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo
